name: Compile C to WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        

    - name: Compile C to WebAssembly
      run: |
        
        emcc hello.c -o hello.html

    - name: Upload WebAssembly files
      uses: actions/upload-artifact@v4
      with:
        name: wasm-files
        path: hello.*
